#ifndef CERT_H

#define CERT_H

const char* root_ca = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIDeTCCAmGgAwIBAgIUY9U1irnU3KqzveGZsg1bZc8WFEUwDQYJKoZIhvcNAQEL\n" \
"BQAwZzELMAkGA1UEBhMCS1IxETAPBgNVBAgTCE5ldyBZb3JrMREwDwYDVQQHEwhO\n" \
"ZXcgWW9yazEQMA4GA1UEChMHQXJkdWlubyBJbmMxDDAKBgNVBAsTA1BLSTEaMBgG\n" \
"A1UEAxMRaW5jb21wYW55LmFyZHVpbm8uY29tMSYwJAYJKoZIhvcNAQkBFhdyZWFs\n" \
"QGFyZHVpbm8uY29tMB4XDTIwMzEyNzE3MjcwMFoXDTMwMzEyNDE3MjcwMFowZzEL\n" \
"MAkGA1UEBhMCS1IxETAPBgNVBAgTCE5ldyBZb3JrMREwDwYDVQQHEwhOZXcgWW9y\n" \
"azEQMA4GA1UEChMHQXJkdWlubyBJbmMxDDAKBgNVBAsTA1BLSTEaMBgGA1UEAxMR\n" \
"aW5jb21wYW55LmFyZHVpbm8uY29tMSYwJAYJKoZIhvcNAQkBFhdyZWFsQGFyZHVp\n" \
"bm8uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtHHX9IDjQvfk\n" \
"ZlqlJlV7UuI6jzE6xJQ4c3X6MVuL6fLW7TazTg32HLV7/lU6eKUzL4l4bsP3lXuE\n" \
"+7V1aFZpSh7g1kKj8p7WxzcClD9gtC9emWXvY8GcWb72Zgg1cMljD5UhQz5dO+Go\n" \
"9XbytYwwpTD13IZTVw/kK/SitOi5PzJh8b" \
"-----END CERTIFICATE-----\n";
#endif